//! NAT networks: a gateway address on a glidex bridge, DHCP from dnsmasq,
//! and masquerading through whatever route the host already uses
//! (spec §10).

use crate::exec::{Cmd, Exec, Program};
use crate::names::{validate_mac, validate_name, MAX_IFNAME};
use crate::net::{route_destinations, Ipv4Net};
use crate::OvsError;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::net::Ipv4Addr;
use std::path::{Path, PathBuf};

pub const DEFAULT_SUPERNET: &str = "10.88.0.0/16";
pub const DNSMASQ_RUN_DIR: &str = "/run/glidex/dnsmasq";
pub const DNSMASQ_LEASE_DIR: &str = "/var/lib/glidex/dnsmasq";
pub const NFT_TABLE: &str = "glidex";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NatSpec {
    pub bridge: String,
    /// `None`: first free /24 in the supernet (spec decision 8).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subnet: Option<Ipv4Net>,
    #[serde(default = "default_true")]
    pub dns: bool,
}

fn default_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NatState {
    pub bridge: String,
    pub subnet: Ipv4Net,
    pub gateway: Ipv4Addr,
    pub pool_start: Ipv4Addr,
    pub pool_end: Ipv4Addr,
    pub dns: bool,
    /// MAC → reserved address; a VM keeps its address across restarts.
    #[serde(default)]
    pub reservations: BTreeMap<String, Ipv4Addr>,
}

impl NatState {
    pub fn new(bridge: &str, subnet: Ipv4Net, dns: bool) -> Result<Self, OvsError> {
        if subnet.prefix() > 29 {
            return Err(OvsError::invalid("NAT subnet must be /29 or larger"));
        }
        let host = |n| subnet.host(n).ok_or_else(|| OvsError::invalid("subnet too small"));
        Ok(Self {
            bridge: bridge.to_string(),
            subnet,
            gateway: host(1)?,
            pool_start: host(2)?,
            pool_end: subnet
                .last_host()
                .ok_or_else(|| OvsError::invalid("subnet too small"))?,
            dns,
            reservations: BTreeMap::new(),
        })
    }

    /// Existing reservation for `mac`, or the lowest free pool address.
    pub fn allocate(&mut self, mac: &str) -> Result<Ipv4Addr, OvsError> {
        validate_mac(mac)?;
        let mac = mac.to_ascii_lowercase();
        if let Some(ip) = self.reservations.get(&mac) {
            return Ok(*ip);
        }
        let used: std::collections::BTreeSet<Ipv4Addr> = self.reservations.values().copied().collect();
        let free = (u32::from(self.pool_start)..=u32::from(self.pool_end))
            .map(Ipv4Addr::from)
            .find(|ip| !used.contains(ip))
            .ok_or_else(|| OvsError::conflict(format!("NAT pool of '{}' is exhausted", self.bridge)))?;
        self.reservations.insert(mac, free);
        Ok(free)
    }

    pub fn release(&mut self, mac: &str) {
        self.reservations.remove(&mac.to_ascii_lowercase());
    }

    pub fn conf_path(&self) -> PathBuf {
        Path::new(DNSMASQ_RUN_DIR).join(format!("{}.conf", self.bridge))
    }

    pub fn hosts_path(&self) -> PathBuf {
        Path::new(DNSMASQ_RUN_DIR).join(format!("{}.hosts", self.bridge))
    }

    pub fn pid_path(&self) -> PathBuf {
        Path::new(DNSMASQ_RUN_DIR).join(format!("{}.pid", self.bridge))
    }

    pub fn lease_path(&self) -> PathBuf {
        Path::new(DNSMASQ_LEASE_DIR).join(format!("{}.leases", self.bridge))
    }

    pub fn dnsmasq_conf(&self) -> String {
        let mut c = format!(
            "# Generated by glidex-netd; do not edit.\n\
             interface={br}\n\
             bind-interfaces\n\
             except-interface=lo\n\
             dhcp-range={start},{end},12h\n\
             dhcp-option=option:router,{gw}\n\
             dhcp-hostsfile={hosts}\n\
             dhcp-leasefile={leases}\n\
             pid-file={pid}\n\
             dhcp-authoritative\n",
            br = self.bridge,
            start = self.pool_start,
            end = self.pool_end,
            gw = self.gateway,
            hosts = self.hosts_path().display(),
            leases = self.lease_path().display(),
            pid = self.pid_path().display(),
        );
        if self.dns {
            // dnsmasq runs on the host, so it can forward to the host's
            // resolvers (including a systemd-resolved stub on 127.0.0.53)
            // even though guests can't reach that stub themselves.
            c.push_str(&format!("listen-address={}\ndhcp-option=option:dns-server,{}\n", self.gateway, self.gateway));
        } else {
            c.push_str("port=0\n");
        }
        c
    }

    pub fn dnsmasq_hosts(&self) -> String {
        self.reservations
            .iter()
            .map(|(mac, ip)| format!("{},{}\n", mac, ip))
            .collect()
    }

    pub fn dnsmasq_args(&self) -> Vec<String> {
        vec![
            "--keep-in-foreground".into(),
            format!("--conf-file={}", self.conf_path().display()),
        ]
    }
}

/// First /24 in `supernet` that overlaps no host route and no other NAT.
/// The default route (`/0`) is ignored: it overlaps everything.
pub fn choose_subnet(
    supernet: Ipv4Net,
    routes: &[Ipv4Net],
    taken: &[Ipv4Net],
) -> Result<Ipv4Net, OvsError> {
    supernet
        .subnets(24)
        .find(|candidate| {
            !routes.iter().any(|r| r.prefix() > 0 && r.overlaps(candidate))
                && !taken.iter().any(|t| t.overlaps(candidate))
        })
        .ok_or_else(|| OvsError::conflict(format!("no free /24 left in {}", supernet)))
}

/// Resolve a `NatSpec` into a state (subnet chosen, collisions refused).
pub fn plan(
    exec: &dyn Exec,
    spec: &NatSpec,
    supernet: Ipv4Net,
    others: &[NatState],
    existing: Option<&NatState>,
) -> Result<NatState, OvsError> {
    validate_name("bridge", &spec.bridge, MAX_IFNAME)?;
    let taken: Vec<Ipv4Net> = others.iter().map(|n| n.subnet).collect();
    // Our own bridge's route (from a previous apply) must not count as a collision.
    let routes: Vec<Ipv4Net> = route_destinations(exec)?
        .into_iter()
        .filter(|r| existing.map_or(true, |e| *r != e.subnet))
        .collect();
    let subnet = match (spec.subnet, existing) {
        (None, Some(e)) => e.subnet,
        (Some(s), _) => {
            if let Some(clash) = taken.iter().find(|t| t.overlaps(&s)) {
                return Err(OvsError::conflict(format!("{} overlaps NAT network {}", s, clash)));
            }
            if let Some(clash) = routes.iter().find(|r| r.prefix() > 0 && r.overlaps(&s)) {
                return Err(OvsError::conflict(format!("{} overlaps host route {}", s, clash)));
            }
            s
        }
        (None, None) => choose_subnet(supernet, &routes, &taken)?,
    };
    let mut state = NatState::new(&spec.bridge, subnet, spec.dns)?;
    if let Some(e) = existing {
        if e.subnet == subnet {
            state.reservations = e.reservations.clone();
        }
    }
    Ok(state)
}

/// Put the gateway address on the bridge's internal interface.
pub fn apply_address(exec: &dyn Exec, state: &NatState) -> Result<(), OvsError> {
    let addr = format!("{}/{}", state.gateway, state.subnet.prefix());
    exec.check(&Cmd::new(Program::Ip, ["addr", "replace", addr.as_str(), "dev", state.bridge.as_str()]))?;
    exec.check(&Cmd::new(Program::Ip, ["link", "set", state.bridge.as_str(), "up"]))?;
    Ok(())
}

pub fn remove_address(exec: &dyn Exec, state: &NatState) -> Result<(), OvsError> {
    let addr = format!("{}/{}", state.gateway, state.subnet.prefix());
    // The bridge may already be gone; that's fine.
    let _ = exec.run(&Cmd::new(Program::Ip, ["addr", "del", addr.as_str(), "dev", state.bridge.as_str()]));
    Ok(())
}

/// Enable IPv4 forwarding if needed. Returns true if glidex changed it.
pub fn ensure_ip_forward(exec: &dyn Exec) -> Result<bool, OvsError> {
    let current = exec
        .read_file(Path::new("/proc/sys/net/ipv4/ip_forward"))
        .unwrap_or_default();
    if current.trim() == "1" {
        return Ok(false);
    }
    exec.check(&Cmd::new(Program::Sysctl, ["-w", "net.ipv4.ip_forward=1"]))?;
    Ok(true)
}

/// The whole `inet glidex` table for all NAT networks, as one atomic
/// `nft -f` script. Creating then deleting the table first makes the
/// script valid whether or not the table exists.
pub fn nft_script(nats: &[NatState]) -> String {
    let mut s = format!(
        "table inet {t}\ndelete table inet {t}\n",
        t = NFT_TABLE
    );
    if nats.is_empty() {
        return s;
    }
    s.push_str(&format!("table inet {} {{\n", NFT_TABLE));
    s.push_str("  chain postrouting {\n    type nat hook postrouting priority srcnat; policy accept;\n");
    for n in nats {
        s.push_str(&format!(
            "    ip saddr {net} ip daddr != {net} masquerade\n",
            net = n.subnet
        ));
    }
    s.push_str("  }\n  chain forward {\n    type filter hook forward priority filter; policy accept;\n");
    for n in nats {
        s.push_str(&format!(
            "    iifname \"{br}\" ip saddr {net} accept\n    oifname \"{br}\" ct state established,related accept\n",
            br = n.bridge,
            net = n.subnet
        ));
    }
    s.push_str("  }\n}\n");
    s
}

pub fn apply_nft(exec: &dyn Exec, nats: &[NatState]) -> Result<(), OvsError> {
    exec.check(&Cmd::new(Program::Nft, ["-f", "-"]).stdin(nft_script(nats)))?;
    Ok(())
}

/// Write the dnsmasq config and hosts file (the process is supervised by
/// netd).
pub fn write_dnsmasq_files(exec: &dyn Exec, state: &NatState) -> Result<(), OvsError> {
    exec.write_file(&state.conf_path(), state.dnsmasq_conf().as_bytes())?;
    exec.write_file(&state.hosts_path(), state.dnsmasq_hosts().as_bytes())?;
    Ok(())
}

pub fn remove_dnsmasq_files(exec: &dyn Exec, state: &NatState) -> Result<(), OvsError> {
    exec.remove_file(&state.conf_path())?;
    exec.remove_file(&state.hosts_path())?;
    exec.remove_file(&state.pid_path())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::exec::{Output, RecordingExec};

    fn net(s: &str) -> Ipv4Net {
        s.parse().unwrap()
    }

    #[test]
    fn picks_first_free_subnet() {
        let sup = net(DEFAULT_SUPERNET);
        assert_eq!(choose_subnet(sup, &[net("0.0.0.0/0")], &[]).unwrap(), net("10.88.0.0/24"));
        assert_eq!(
            choose_subnet(sup, &[net("10.88.0.0/24")], &[net("10.88.1.0/24")]).unwrap(),
            net("10.88.2.0/24")
        );
        // A host route covering the whole supernet leaves nothing.
        assert!(choose_subnet(sup, &[net("10.0.0.0/8")], &[]).is_err());
    }

    #[test]
    fn plan_uses_default_and_refuses_collisions() {
        let exec = RecordingExec::new();
        exec.on("ip -4 -j route show", Output::ok(r#"[{"dst":"default"},{"dst":"10.0.0.0/24"}]"#));
        let spec = NatSpec { bridge: "gxbr-nat".into(), subnet: None, dns: true };
        let state = plan(&exec, &spec, net(DEFAULT_SUPERNET), &[], None).unwrap();
        assert_eq!(state.subnet, net("10.88.0.0/24"));
        assert_eq!(state.gateway.to_string(), "10.88.0.1");
        assert_eq!(state.pool_start.to_string(), "10.88.0.2");
        assert_eq!(state.pool_end.to_string(), "10.88.0.254");

        let clash = NatSpec { subnet: Some(net("10.0.0.0/24")), ..spec.clone() };
        assert!(matches!(plan(&exec, &clash, net(DEFAULT_SUPERNET), &[], None), Err(OvsError::Conflict { .. })));

        // Re-planning keeps the subnet and reservations even though the
        // bridge's own route now exists.
        let exec = RecordingExec::new();
        exec.on("ip -4 -j route show", Output::ok(r#"[{"dst":"10.88.0.0/24","dev":"gxbr-nat"}]"#));
        let mut existing = state.clone();
        existing.allocate("02:00:00:00:00:01").unwrap();
        let again = plan(&exec, &spec, net(DEFAULT_SUPERNET), &[], Some(&existing)).unwrap();
        assert_eq!(again.subnet, existing.subnet);
        assert_eq!(again.reservations.len(), 1);
    }

    #[test]
    fn reservations_are_stable_and_reused() {
        let mut s = NatState::new("gxbr-nat", net("10.88.0.0/24"), true).unwrap();
        let a = s.allocate("02:AA:00:00:00:01").unwrap();
        let b = s.allocate("02:aa:00:00:00:02").unwrap();
        assert_eq!(a.to_string(), "10.88.0.2");
        assert_eq!(b.to_string(), "10.88.0.3");
        assert_eq!(s.allocate("02:aa:00:00:00:01").unwrap(), a, "case-insensitive, stable");
        s.release("02:aa:00:00:00:01");
        assert_eq!(s.allocate("02:aa:00:00:00:09").unwrap(), a, "freed address reused");
        assert!(s.allocate("ff:ff:ff:ff:ff:ff").is_err());
        assert_eq!(s.dnsmasq_hosts(), "02:aa:00:00:00:02,10.88.0.3\n02:aa:00:00:00:09,10.88.0.2\n");
    }

    #[test]
    fn small_pool_exhausts() {
        let mut s = NatState::new("gxbr-t", net("10.88.9.0/29"), false).unwrap();
        for i in 0..5 {
            s.allocate(&format!("02:00:00:00:00:0{}", i)).unwrap();
        }
        assert!(matches!(s.allocate("02:00:00:00:00:09"), Err(OvsError::Conflict { .. })));
    }

    #[test]
    fn nft_script_is_atomic_and_complete() {
        let a = NatState::new("gxbr-nat", net("10.88.0.0/24"), true).unwrap();
        let script = nft_script(&[a]);
        assert!(script.starts_with("table inet glidex\ndelete table inet glidex\n"));
        assert!(script.contains("ip saddr 10.88.0.0/24 ip daddr != 10.88.0.0/24 masquerade"));
        assert!(script.contains("iifname \"gxbr-nat\" ip saddr 10.88.0.0/24 accept"));
        assert!(!script.contains("oifname \"eth"), "no outgoing interface is pinned");
        assert_eq!(nft_script(&[]), "table inet glidex\ndelete table inet glidex\n");
    }

    #[test]
    fn dnsmasq_config() {
        let s = NatState::new("gxbr-nat", net("10.88.0.0/24"), true).unwrap();
        let conf = s.dnsmasq_conf();
        for line in [
            "interface=gxbr-nat",
            "bind-interfaces",
            "dhcp-range=10.88.0.2,10.88.0.254,12h",
            "dhcp-option=option:router,10.88.0.1",
            "listen-address=10.88.0.1",
            "dhcp-hostsfile=/run/glidex/dnsmasq/gxbr-nat.hosts",
        ] {
            assert!(conf.lines().any(|l| l == line), "missing {line}\n{conf}");
        }
        let no_dns = NatState { dns: false, ..s };
        assert!(no_dns.dnsmasq_conf().lines().any(|l| l == "port=0"));
    }

    #[test]
    fn host_changes() {
        let exec = RecordingExec::new();
        exec.file("/proc/sys/net/ipv4/ip_forward", "0\n");
        assert!(ensure_ip_forward(&exec).unwrap());
        assert!(exec.calls().contains(&"sysctl -w net.ipv4.ip_forward=1".to_string()));
        let exec = RecordingExec::new();
        exec.file("/proc/sys/net/ipv4/ip_forward", "1\n");
        assert!(!ensure_ip_forward(&exec).unwrap());
        assert!(exec.calls().is_empty());

        let exec = RecordingExec::new();
        let s = NatState::new("gxbr-nat", net("10.88.0.0/24"), true).unwrap();
        apply_address(&exec, &s).unwrap();
        assert_eq!(exec.calls(), vec!["ip addr replace 10.88.0.1/24 dev gxbr-nat", "ip link set gxbr-nat up"]);
    }
}
