//! NAT networks: a gateway address on a glidex bridge, DHCP from dnsmasq,
//! and masquerading through whatever route the host already uses
//! (spec §10).

use crate::exec::{Cmd, Exec, Program};
use crate::names::{validate_mac, validate_name, MAX_IFNAME};
use crate::net::{route_destinations, Ipv4Net};
use crate::OvsError;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::net::Ipv4Addr;
use std::path::{Path, PathBuf};

pub const DEFAULT_SUPERNET: &str = "10.88.0.0/16";
pub const DNSMASQ_RUN_DIR: &str = "/run/glidex/dnsmasq";
pub const DNSMASQ_LEASE_DIR: &str = "/var/lib/glidex/dnsmasq";
pub const NFT_TABLE: &str = "glidex";
/// glidex's chain in iptables' `filter` table, for hosts whose FORWARD
/// policy would otherwise drop NAT traffic (see [`apply_iptables`]).
pub const IPT_CHAIN: &str = "GLIDEX-FORWARD";

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NatSpec {
    pub bridge: String,
    /// `None`: first free /24 in the supernet (spec decision 8).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subnet: Option<Ipv4Net>,
    #[serde(default = "default_true")]
    pub dns: bool,
}

fn default_true() -> bool {
    true
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NatState {
    pub bridge: String,
    pub subnet: Ipv4Net,
    pub gateway: Ipv4Addr,
    pub pool_start: Ipv4Addr,
    pub pool_end: Ipv4Addr,
    pub dns: bool,
    /// MAC → reserved address; a VM keeps its address across restarts.
    #[serde(default)]
    pub reservations: BTreeMap<String, Ipv4Addr>,
}

impl NatState {
    pub fn new(bridge: &str, subnet: Ipv4Net, dns: bool) -> Result<Self, OvsError> {
        if subnet.prefix() > 29 {
            return Err(OvsError::invalid("NAT subnet must be /29 or larger"));
        }
        let host = |n| subnet.host(n).ok_or_else(|| OvsError::invalid("subnet too small"));
        Ok(Self {
            bridge: bridge.to_string(),
            subnet,
            gateway: host(1)?,
            pool_start: host(2)?,
            pool_end: subnet
                .last_host()
                .ok_or_else(|| OvsError::invalid("subnet too small"))?,
            dns,
            reservations: BTreeMap::new(),
        })
    }

    /// Existing reservation for `mac`, or the lowest free pool address.
    pub fn allocate(&mut self, mac: &str) -> Result<Ipv4Addr, OvsError> {
        self.allocate_avoiding(mac, &BTreeMap::new())
    }

    /// Like [`allocate`](Self::allocate), but a new reservation skips
    /// addresses dnsmasq still has leased to another MAC (`leases`, from
    /// [`active_leases`]): dnsmasq won't hand a reserved address out while
    /// that lease lasts, so the VM would get a pool address instead. Such
    /// addresses are used only when nothing else is free.
    pub fn allocate_avoiding(&mut self, mac: &str, leases: &BTreeMap<Ipv4Addr, String>) -> Result<Ipv4Addr, OvsError> {
        validate_mac(mac)?;
        let mac = mac.to_ascii_lowercase();
        if let Some(ip) = self.reservations.get(&mac) {
            return Ok(*ip);
        }
        let used: std::collections::BTreeSet<Ipv4Addr> = self.reservations.values().copied().collect();
        let free: Vec<Ipv4Addr> = (u32::from(self.pool_start)..=u32::from(self.pool_end))
            .map(Ipv4Addr::from)
            .filter(|ip| !used.contains(ip))
            .collect();
        let leased_elsewhere = |ip: &Ipv4Addr| leases.get(ip).is_some_and(|m| *m != mac);
        let pick = free
            .iter()
            .find(|ip| !leased_elsewhere(ip))
            .or_else(|| free.first())
            .copied()
            .ok_or_else(|| OvsError::conflict(format!("NAT pool of '{}' is exhausted", self.bridge)))?;
        self.reservations.insert(mac, pick);
        Ok(pick)
    }

    pub fn release(&mut self, mac: &str) {
        self.reservations.remove(&mac.to_ascii_lowercase());
    }

    pub fn conf_path(&self) -> PathBuf {
        Path::new(DNSMASQ_RUN_DIR).join(format!("{}.conf", self.bridge))
    }

    pub fn hosts_path(&self) -> PathBuf {
        Path::new(DNSMASQ_RUN_DIR).join(format!("{}.hosts", self.bridge))
    }

    pub fn pid_path(&self) -> PathBuf {
        Path::new(DNSMASQ_RUN_DIR).join(format!("{}.pid", self.bridge))
    }

    pub fn lease_path(&self) -> PathBuf {
        Path::new(DNSMASQ_LEASE_DIR).join(format!("{}.leases", self.bridge))
    }

    pub fn dnsmasq_conf(&self) -> String {
        let mut c = format!(
            "# Generated by glidex-netd; do not edit.\n\
             interface={br}\n\
             bind-interfaces\n\
             except-interface=lo\n\
             dhcp-range={start},{end},12h\n\
             dhcp-option=option:router,{gw}\n\
             dhcp-hostsfile={hosts}\n\
             dhcp-leasefile={leases}\n\
             pid-file={pid}\n\
             dhcp-authoritative\n",
            br = self.bridge,
            start = self.pool_start,
            end = self.pool_end,
            gw = self.gateway,
            hosts = self.hosts_path().display(),
            leases = self.lease_path().display(),
            pid = self.pid_path().display(),
        );
        if self.dns {
            // dnsmasq runs on the host, so it can forward to the host's
            // resolvers (including a systemd-resolved stub on 127.0.0.53)
            // even though guests can't reach that stub themselves.
            c.push_str(&format!("listen-address={}\ndhcp-option=option:dns-server,{}\n", self.gateway, self.gateway));
        } else {
            c.push_str("port=0\n");
        }
        c
    }

    pub fn dnsmasq_hosts(&self) -> String {
        self.reservations
            .iter()
            .map(|(mac, ip)| format!("{},{}\n", mac, ip))
            .collect()
    }

    pub fn dnsmasq_args(&self) -> Vec<String> {
        vec![
            "--keep-in-foreground".into(),
            format!("--conf-file={}", self.conf_path().display()),
        ]
    }
}

/// First /24 in `supernet` that overlaps no host route and no other NAT.
/// The default route (`/0`) is ignored: it overlaps everything.
pub fn choose_subnet(
    supernet: Ipv4Net,
    routes: &[Ipv4Net],
    taken: &[Ipv4Net],
) -> Result<Ipv4Net, OvsError> {
    supernet
        .subnets(24)
        .find(|candidate| {
            !routes.iter().any(|r| r.prefix() > 0 && r.overlaps(candidate))
                && !taken.iter().any(|t| t.overlaps(candidate))
        })
        .ok_or_else(|| OvsError::conflict(format!("no free /24 left in {}", supernet)))
}

/// Resolve a `NatSpec` into a state (subnet chosen, collisions refused).
pub fn plan(
    exec: &dyn Exec,
    spec: &NatSpec,
    supernet: Ipv4Net,
    others: &[NatState],
    existing: Option<&NatState>,
) -> Result<NatState, OvsError> {
    validate_name("bridge", &spec.bridge, MAX_IFNAME)?;
    let taken: Vec<Ipv4Net> = others.iter().map(|n| n.subnet).collect();
    // Our own bridge's route (from a previous apply) must not count as a collision.
    let routes: Vec<Ipv4Net> = route_destinations(exec)?
        .into_iter()
        .filter(|r| existing.map_or(true, |e| *r != e.subnet))
        .collect();
    let subnet = match (spec.subnet, existing) {
        (None, Some(e)) => e.subnet,
        (Some(s), _) => {
            if let Some(clash) = taken.iter().find(|t| t.overlaps(&s)) {
                return Err(OvsError::conflict(format!("{} overlaps NAT network {}", s, clash)));
            }
            if let Some(clash) = routes.iter().find(|r| r.prefix() > 0 && r.overlaps(&s)) {
                return Err(OvsError::conflict(format!("{} overlaps host route {}", s, clash)));
            }
            s
        }
        (None, None) => choose_subnet(supernet, &routes, &taken)?,
    };
    let mut state = NatState::new(&spec.bridge, subnet, spec.dns)?;
    if let Some(e) = existing {
        if e.subnet == subnet {
            state.reservations = e.reservations.clone();
        }
    }
    Ok(state)
}

/// Put the gateway address on the bridge's internal interface.
pub fn apply_address(exec: &dyn Exec, state: &NatState) -> Result<(), OvsError> {
    let addr = format!("{}/{}", state.gateway, state.subnet.prefix());
    exec.check(&Cmd::new(Program::Ip, ["addr", "replace", addr.as_str(), "dev", state.bridge.as_str()]))?;
    exec.check(&Cmd::new(Program::Ip, ["link", "set", state.bridge.as_str(), "up"]))?;
    Ok(())
}

pub fn remove_address(exec: &dyn Exec, state: &NatState) -> Result<(), OvsError> {
    let addr = format!("{}/{}", state.gateway, state.subnet.prefix());
    // The bridge may already be gone; that's fine.
    let _ = exec.run(&Cmd::new(Program::Ip, ["addr", "del", addr.as_str(), "dev", state.bridge.as_str()]));
    Ok(())
}

/// Enable IPv4 forwarding if needed. Returns true if glidex changed it.
pub fn ensure_ip_forward(exec: &dyn Exec) -> Result<bool, OvsError> {
    let current = exec
        .read_file(Path::new("/proc/sys/net/ipv4/ip_forward"))
        .unwrap_or_default();
    if current.trim() == "1" {
        return Ok(false);
    }
    exec.check(&Cmd::new(Program::Sysctl, ["-w", "net.ipv4.ip_forward=1"]))?;
    Ok(true)
}

/// The whole `inet glidex` table for all NAT networks, as one atomic
/// `nft -f` script. Creating then deleting the table first makes the
/// script valid whether or not the table exists.
pub fn nft_script(nats: &[NatState]) -> String {
    let mut s = format!(
        "table inet {t}\ndelete table inet {t}\n",
        t = NFT_TABLE
    );
    if nats.is_empty() {
        return s;
    }
    s.push_str(&format!("table inet {} {{\n", NFT_TABLE));
    s.push_str("  chain postrouting {\n    type nat hook postrouting priority srcnat; policy accept;\n");
    for n in nats {
        s.push_str(&format!(
            "    ip saddr {net} ip daddr != {net} masquerade\n",
            net = n.subnet
        ));
    }
    s.push_str("  }\n  chain forward {\n    type filter hook forward priority filter; policy accept;\n");
    for n in nats {
        s.push_str(&format!(
            "    iifname \"{br}\" ip saddr {net} accept\n    oifname \"{br}\" ct state established,related accept\n",
            br = n.bridge,
            net = n.subnet
        ));
    }
    s.push_str("  }\n}\n");
    s
}

pub fn apply_nft(exec: &dyn Exec, nats: &[NatState]) -> Result<(), OvsError> {
    exec.check(&Cmd::new(Program::Nft, ["-f", "-"]).stdin(nft_script(nats)))?;
    Ok(())
}

/// Where to hook [`IPT_CHAIN`] in so a dropping iptables FORWARD chain
/// lets NAT traffic through. An accept in our own nftables table can't
/// overrule a drop in another table at the same hook, so the accept has to
/// live in the dropping chain itself: Docker's `DOCKER-USER` (Docker sets
/// FORWARD to DROP and keeps that chain for admin rules), else FORWARD
/// when its policy is DROP. `None`: nothing drops forwarded traffic, or
/// iptables isn't installed.
pub fn iptables_hook(exec: &dyn Exec) -> Option<&'static str> {
    let rules = |chain: &str| {
        exec.run(&Cmd::new(Program::Iptables, ["-w", "-S", chain]))
            .ok()
            .filter(|o| o.status == 0)
            .map(|o| o.stdout_str())
            .unwrap_or_default()
    };
    if rules("DOCKER-USER").lines().any(|l| l.trim() == "-N DOCKER-USER") {
        Some("DOCKER-USER")
    } else if rules("FORWARD").lines().any(|l| l.trim() == "-P FORWARD DROP") {
        Some("FORWARD")
    } else {
        None
    }
}

/// The `-A` rules of [`IPT_CHAIN`]: the same accepts as the nftables
/// forward chain.
pub fn iptables_rules(nats: &[NatState]) -> Vec<Vec<String>> {
    nats.iter()
        .flat_map(|n| {
            let (br, net) = (n.bridge.as_str(), n.subnet.to_string());
            [
                vec!["-i", br, "-s", &net, "-j", "ACCEPT"],
                vec!["-o", br, "-m", "conntrack", "--ctstate", "RELATED,ESTABLISHED", "-j", "ACCEPT"],
            ]
            .map(|r| {
                ["-w", "-A", IPT_CHAIN]
                    .into_iter()
                    .chain(r)
                    .map(String::from)
                    .collect()
            })
        })
        .collect()
}

/// Bring [`IPT_CHAIN`] in line with `nats`: rebuilt and jumped to from
/// [`iptables_hook`]'s chain when something drops forwarded traffic,
/// removed (chain and jumps) otherwise or once no NAT networks remain.
pub fn apply_iptables(exec: &dyn Exec, nats: &[NatState]) -> Result<(), OvsError> {
    let ipt = |args: &[&str]| Cmd::new(Program::Iptables, args.iter().copied());
    let ok = |cmd: Cmd| exec.run(&cmd).is_ok_and(|o| o.status == 0);
    let hook = iptables_hook(exec).filter(|_| !nats.is_empty());
    // glidex only ever inserts one jump, so one `-D` per chain clears a
    // stale one (it fails harmlessly when there's none, or no iptables).
    for chain in ["DOCKER-USER", "FORWARD"] {
        if Some(chain) != hook {
            ok(ipt(&["-w", "-D", chain, "-j", IPT_CHAIN]));
        }
    }
    let Some(hook) = hook else {
        ok(ipt(&["-w", "-F", IPT_CHAIN]));
        ok(ipt(&["-w", "-X", IPT_CHAIN]));
        return Ok(());
    };
    if !ok(ipt(&["-w", "-F", IPT_CHAIN])) {
        exec.check(&ipt(&["-w", "-N", IPT_CHAIN]))?;
    }
    for rule in iptables_rules(nats) {
        exec.check(&Cmd::new(Program::Iptables, rule))?;
    }
    if !ok(ipt(&["-w", "-C", hook, "-j", IPT_CHAIN])) {
        exec.check(&ipt(&["-w", "-I", hook, "1", "-j", IPT_CHAIN]))?;
    }
    Ok(())
}

/// Write the dnsmasq config and hosts file (the process is supervised by
/// netd).
pub fn write_dnsmasq_files(exec: &dyn Exec, state: &NatState) -> Result<(), OvsError> {
    exec.write_file(&state.conf_path(), state.dnsmasq_conf().as_bytes())?;
    exec.write_file(&state.hosts_path(), state.dnsmasq_hosts().as_bytes())?;
    Ok(())
}

/// Remove dnsmasq's files for a deleted network, leases included: a
/// recreated network starts its reservations over, and old leases would
/// block them.
pub fn remove_dnsmasq_files(exec: &dyn Exec, state: &NatState) -> Result<(), OvsError> {
    exec.remove_file(&state.conf_path())?;
    exec.remove_file(&state.hosts_path())?;
    exec.remove_file(&state.pid_path())?;
    exec.remove_file(&state.lease_path())?;
    Ok(())
}

/// Unexpired leases in a dnsmasq lease file (`<expiry> <mac> <ip> ...`
/// per line; expiry 0 = infinite), as address → lowercase MAC.
pub fn active_leases(contents: &str, now_unix: u64) -> BTreeMap<Ipv4Addr, String> {
    contents
        .lines()
        .filter_map(|l| {
            let mut f = l.split_whitespace();
            let expiry: u64 = f.next()?.parse().ok()?;
            let mac = f.next()?.to_ascii_lowercase();
            let ip: Ipv4Addr = f.next()?.parse().ok()?;
            (expiry == 0 || expiry > now_unix).then_some((ip, mac))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::exec::{Output, RecordingExec};

    fn net(s: &str) -> Ipv4Net {
        s.parse().unwrap()
    }

    #[test]
    fn picks_first_free_subnet() {
        let sup = net(DEFAULT_SUPERNET);
        assert_eq!(choose_subnet(sup, &[net("0.0.0.0/0")], &[]).unwrap(), net("10.88.0.0/24"));
        assert_eq!(
            choose_subnet(sup, &[net("10.88.0.0/24")], &[net("10.88.1.0/24")]).unwrap(),
            net("10.88.2.0/24")
        );
        // A host route covering the whole supernet leaves nothing.
        assert!(choose_subnet(sup, &[net("10.0.0.0/8")], &[]).is_err());
    }

    #[test]
    fn plan_uses_default_and_refuses_collisions() {
        let exec = RecordingExec::new();
        exec.on("ip -4 -j route show", Output::ok(r#"[{"dst":"default"},{"dst":"10.0.0.0/24"}]"#));
        let spec = NatSpec { bridge: "gxbr-nat".into(), subnet: None, dns: true };
        let state = plan(&exec, &spec, net(DEFAULT_SUPERNET), &[], None).unwrap();
        assert_eq!(state.subnet, net("10.88.0.0/24"));
        assert_eq!(state.gateway.to_string(), "10.88.0.1");
        assert_eq!(state.pool_start.to_string(), "10.88.0.2");
        assert_eq!(state.pool_end.to_string(), "10.88.0.254");

        let clash = NatSpec { subnet: Some(net("10.0.0.0/24")), ..spec.clone() };
        assert!(matches!(plan(&exec, &clash, net(DEFAULT_SUPERNET), &[], None), Err(OvsError::Conflict { .. })));

        // Re-planning keeps the subnet and reservations even though the
        // bridge's own route now exists.
        let exec = RecordingExec::new();
        exec.on("ip -4 -j route show", Output::ok(r#"[{"dst":"10.88.0.0/24","dev":"gxbr-nat"}]"#));
        let mut existing = state.clone();
        existing.allocate("02:00:00:00:00:01").unwrap();
        let again = plan(&exec, &spec, net(DEFAULT_SUPERNET), &[], Some(&existing)).unwrap();
        assert_eq!(again.subnet, existing.subnet);
        assert_eq!(again.reservations.len(), 1);
    }

    #[test]
    fn reservations_are_stable_and_reused() {
        let mut s = NatState::new("gxbr-nat", net("10.88.0.0/24"), true).unwrap();
        let a = s.allocate("02:AA:00:00:00:01").unwrap();
        let b = s.allocate("02:aa:00:00:00:02").unwrap();
        assert_eq!(a.to_string(), "10.88.0.2");
        assert_eq!(b.to_string(), "10.88.0.3");
        assert_eq!(s.allocate("02:aa:00:00:00:01").unwrap(), a, "case-insensitive, stable");
        s.release("02:aa:00:00:00:01");
        assert_eq!(s.allocate("02:aa:00:00:00:09").unwrap(), a, "freed address reused");
        assert!(s.allocate("ff:ff:ff:ff:ff:ff").is_err());
        assert_eq!(s.dnsmasq_hosts(), "02:aa:00:00:00:02,10.88.0.3\n02:aa:00:00:00:09,10.88.0.2\n");
    }

    #[test]
    fn allocation_skips_addresses_leased_to_other_macs() {
        // A deleted VM's lease on .2 outlives its reservation.
        let leases = active_leases(
            "2000 02:89:53:f9:ac:2d 10.88.0.2 * ff:b5\n\
             500 02:00:00:00:00:77 10.88.0.3 * ff:00\n\
             0 02:AA:00:00:00:01 10.88.0.4 host *\n\
             garbage line\n",
            1000,
        );
        assert_eq!(leases.len(), 2, "expired and malformed lines dropped: {leases:?}");
        assert_eq!(leases[&"10.88.0.4".parse().unwrap()], "02:aa:00:00:00:01", "infinite lease kept, MAC lowercased");
        let mut s = NatState::new("gxbr-nat", net("10.88.0.0/24"), true).unwrap();
        assert_eq!(s.allocate_avoiding("02:aa:00:00:00:09", &leases).unwrap().to_string(), "10.88.0.3", ".2 is still leased, .3 expired");
        // A MAC's own lease doesn't block it (.2 is still someone else's).
        assert_eq!(s.allocate_avoiding("02:aa:00:00:00:01", &leases).unwrap().to_string(), "10.88.0.4");
    }

    #[test]
    fn leased_addresses_used_only_when_nothing_else_is_free() {
        let mut s = NatState::new("gxbr-t", net("10.88.9.0/29"), false).unwrap();
        let leases: BTreeMap<Ipv4Addr, String> = (2..=6).map(|n| (format!("10.88.9.{n}").parse().unwrap(), "02:ff:00:00:00:01".to_string())).collect();
        assert_eq!(s.allocate_avoiding("02:00:00:00:00:01", &leases).unwrap().to_string(), "10.88.9.2");
    }

    #[test]
    fn small_pool_exhausts() {
        let mut s = NatState::new("gxbr-t", net("10.88.9.0/29"), false).unwrap();
        for i in 0..5 {
            s.allocate(&format!("02:00:00:00:00:0{}", i)).unwrap();
        }
        assert!(matches!(s.allocate("02:00:00:00:00:09"), Err(OvsError::Conflict { .. })));
    }

    #[test]
    fn nft_script_is_atomic_and_complete() {
        let a = NatState::new("gxbr-nat", net("10.88.0.0/24"), true).unwrap();
        let script = nft_script(&[a]);
        assert!(script.starts_with("table inet glidex\ndelete table inet glidex\n"));
        assert!(script.contains("ip saddr 10.88.0.0/24 ip daddr != 10.88.0.0/24 masquerade"));
        assert!(script.contains("iifname \"gxbr-nat\" ip saddr 10.88.0.0/24 accept"));
        assert!(!script.contains("oifname \"eth"), "no outgoing interface is pinned");
        assert_eq!(nft_script(&[]), "table inet glidex\ndelete table inet glidex\n");
    }

    #[test]
    fn iptables_hook_prefers_docker_user() {
        let exec = RecordingExec::new();
        assert_eq!(iptables_hook(&exec), None, "empty output: nothing drops");

        let exec = RecordingExec::new();
        exec.on("iptables -w -S FORWARD", Output::ok("-P FORWARD DROP\n-A FORWARD -j DOCKER-USER\n"));
        assert_eq!(iptables_hook(&exec), Some("FORWARD"));
        exec.on("iptables -w -S DOCKER-USER", Output::ok("-N DOCKER-USER\n"));
        assert_eq!(iptables_hook(&exec), Some("DOCKER-USER"));

        let exec = RecordingExec::new();
        exec.on("iptables -w -S FORWARD", Output::ok("-P FORWARD ACCEPT\n"));
        exec.on("iptables -w -S DOCKER-USER", Output::failed(1, "No chain/target/match by that name."));
        assert_eq!(iptables_hook(&exec), None);
    }

    #[test]
    fn apply_iptables_behind_docker() {
        let a = NatState::new("gxbr-nat", net("10.88.0.0/24"), true).unwrap();
        let exec = RecordingExec::new();
        exec.on("iptables -w -S DOCKER-USER", Output::ok("-N DOCKER-USER\n"));
        exec.on("iptables -w -F GLIDEX-FORWARD", Output::failed(1, "No chain"));
        exec.on("iptables -w -C DOCKER-USER", Output::failed(1, "Bad rule"));
        apply_iptables(&exec, &[a.clone()]).unwrap();
        let calls = exec.calls();
        let after_detect: Vec<&str> = calls.iter().skip(1).map(String::as_str).collect();
        assert_eq!(after_detect, [
            "iptables -w -D FORWARD -j GLIDEX-FORWARD",
            "iptables -w -F GLIDEX-FORWARD",
            "iptables -w -N GLIDEX-FORWARD",
            "iptables -w -A GLIDEX-FORWARD -i gxbr-nat -s 10.88.0.0/24 -j ACCEPT",
            "iptables -w -A GLIDEX-FORWARD -o gxbr-nat -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT",
            "iptables -w -C DOCKER-USER -j GLIDEX-FORWARD",
            "iptables -w -I DOCKER-USER 1 -j GLIDEX-FORWARD",
        ]);

        // Re-applying keeps the existing chain and jump.
        let exec = RecordingExec::new();
        exec.on("iptables -w -S DOCKER-USER", Output::ok("-N DOCKER-USER\n"));
        apply_iptables(&exec, &[a]).unwrap();
        assert!(!exec.calls().iter().any(|c| c.contains(" -N ") || c.contains(" -I ")), "{:#?}", exec.calls());
    }

    #[test]
    fn apply_iptables_removes_chain_when_unneeded() {
        let a = NatState::new("gxbr-nat", net("10.88.0.0/24"), true).unwrap();
        for nats in [vec![], vec![a]] {
            let exec = RecordingExec::new();
            if nats.is_empty() {
                exec.on("iptables -w -S DOCKER-USER", Output::ok("-N DOCKER-USER\n"));
            }
            apply_iptables(&exec, &nats).unwrap();
            let calls = exec.calls();
            for c in [
                "iptables -w -D DOCKER-USER -j GLIDEX-FORWARD",
                "iptables -w -D FORWARD -j GLIDEX-FORWARD",
                "iptables -w -F GLIDEX-FORWARD",
                "iptables -w -X GLIDEX-FORWARD",
            ] {
                assert!(calls.iter().any(|x| x == c), "missing {c}: {calls:#?}");
            }
            assert!(!calls.iter().any(|c| c.contains(" -A ")), "{calls:#?}");
        }
    }

    #[test]
    fn dnsmasq_config() {
        let s = NatState::new("gxbr-nat", net("10.88.0.0/24"), true).unwrap();
        let conf = s.dnsmasq_conf();
        for line in [
            "interface=gxbr-nat",
            "bind-interfaces",
            "dhcp-range=10.88.0.2,10.88.0.254,12h",
            "dhcp-option=option:router,10.88.0.1",
            "listen-address=10.88.0.1",
            "dhcp-hostsfile=/run/glidex/dnsmasq/gxbr-nat.hosts",
        ] {
            assert!(conf.lines().any(|l| l == line), "missing {line}\n{conf}");
        }
        let no_dns = NatState { dns: false, ..s };
        assert!(no_dns.dnsmasq_conf().lines().any(|l| l == "port=0"));
    }

    #[test]
    fn host_changes() {
        let exec = RecordingExec::new();
        exec.file("/proc/sys/net/ipv4/ip_forward", "0\n");
        assert!(ensure_ip_forward(&exec).unwrap());
        assert!(exec.calls().contains(&"sysctl -w net.ipv4.ip_forward=1".to_string()));
        let exec = RecordingExec::new();
        exec.file("/proc/sys/net/ipv4/ip_forward", "1\n");
        assert!(!ensure_ip_forward(&exec).unwrap());
        assert!(exec.calls().is_empty());

        let exec = RecordingExec::new();
        let s = NatState::new("gxbr-nat", net("10.88.0.0/24"), true).unwrap();
        apply_address(&exec, &s).unwrap();
        assert_eq!(exec.calls(), vec!["ip addr replace 10.88.0.1/24 dev gxbr-nat", "ip link set gxbr-nat up"]);
    }
}
