[package]
name = "glidex-install"
version.workspace = true
edition.workspace = true

[[bin]]
name = "glidex-install"
path = "src/main.rs"

[dependencies]
glidex-ovs = { path = "../glidex-ovs" }
glidex-netd = { path = "../glidex-netd" }
serde_json = { workspace = true }
anyhow = "1"
colored = "3"
dirs = "6"
libc = "0.2"
tempfile = "3"
